language: cpp

cache:
 apt: true

env:
  - RUN_TESTS=false USE_VTK=OFF

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - tcl-dev
      - tk-dev
      - libgl2ps-dev
      - libfreeimage-dev
      - libtbb-dev
      - tclthread
      - libgl1-mesa-dev
      - libxmu-dev
      - libxi-dev
      - xsltproc
      - doxygen
      - ninja-build
      - libvtk-dev
      
matrix:
  include:
  - os: linux
    compiler: gcc
    env: USE_VTK=ON
    dist: xenial
  - os: linux
    compiler: gcc
    env: USE_VTK=ON
    dist: bionic
  - os: linux
    compiler: gcc
    env: USE_VTK=OFF
    dist: focal
  - os: linux
    compiler: gcc
    env: USE_VTK=ON
    dist: focal
  - os: linux
    compiler: clang
    env: USE_VTK=ON
    dist: focal
  - os: osx
    osx_image: xcode11.6
    compiler: clang
  - os: osx
    osx_image: xcode12
    compiler: clang
  - os: osx
    osx_image: xcode9.3beta
    compiler: clang

before_install:
  # osx
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install freetype;
        brew install freeimage;
        brew install gl2ps;
        brew install doxygen;
    fi
  # linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        eval "${MATRIX_EVAL}";
    fi

before_script:
#  Initialize xvfb server
#  Depth is necessary, otherwise DRAWEXE exits with this message:
#    Tcl Exception: ** Exception ** 0x7fee03adb307 : Aspect_WindowDefinitionError: Xw_Window, couldn't find compatible Visual (RGBA, double-buffered)
#  Remove OCCT tests which are going to be skipped
#  because of missing data files.  We must use -name
#  to filter out 'begin' or 'end' files.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x16";
        find tests -type f -name '[A-Z][0-9]' -o -name 'Z[A-Z][0-9]' -o -name 'bu[gc]*' | xargs grep -l locate_data_file /dev/null | xargs rm -f;
        rm -rf tests/chamfer tests/de tests/mesh tests/perf/*_mesh_*;
    fi

script:
  - mkdir cmake-build
  - cd cmake-build
  - cmake .. -DUSE_VTK=$USE_VTK -USE_FREEIMAGE=ON
  - make && make install

after_script:
  - test ! -r occt/summary.xml || xsltproc --param duration 1 ../.travis.xsl occt/summary.xml
  - if [ -r occt/summary.xml ]; then
        xsltproc ../.travis.xsl occt/summary.xml > occt/summary.failed;
        if [ -s occt/summary.failed ]; then
            echo "FAILED TESTS:";
            cat occt/summary.failed;
            for file in $(cat occt/summary.failed); do head -n -1 occt/$file.{tcl,log}; done;
        fi;
    fi

branches:
  only:
    - master
    - /^review/
    - oce/patches
